baseurl = "http://gildia-catering.me6iaton.ru/"
title = "gildia-catering.ru"
author =  "Anton Mamrashev"
copyright = "Copyright (c) 2015, Anton Mamrashev; all rights reserved."

[params]

[params.slider]
timeout = 5000
timeoutHover = 200

[params.portfolio]
title = "Портфолио"
image = "http://lorempixel.com/807/454/food"
content = """
Компания имеет большой опыт в организации выездных банкетов. Наша компания одна из немногих , кто сегодня имеет такую материальную базу , которая позволяет обслужить 5000 и более гостей. Многие солидные и уважаемые компании доверили организацию и проведение своего корпоративного праздника.
"""

