baseurl = "http://gildia-catering.ru/"
title = "gildia-catering.ru"
author =  "Anton Mamrashev"
copyright = "Copyright (c) 2015, Anton Mamrashev; all rights reserved."
Paginate = 9

[params.seo]
  title = "gildia-catering.ru - "

[params.slider]
  timeout = 5000
  timeoutHover = 200

[params.footer]
  left = """
  © 2015, Гильдия Кейтеринг - организация праздников, банкеты, фуршеты, свадьбы, корпоративные мероприятия. Все права защищены.
  <br>
  Наш адрес: г. Москва, Мясницкий проезд, д.2/1 стр.1. (<a href="/contacts/">схема проезда</a>)
  <br>
  Наш телефон: +7 (499) 411-19-62 (многоканальный)
  """
  right = """
  <a target="_blank" href="http://brainstorage.me/me6iaton">©Создание сайта <br> Anton Mamrashev</a>
  """

[params.index]
  title = "Главная"
  image = ""
  description = """

  """
[params.services]
  title = "Услуги"
  image = ""
  description = """

  """
[params.menu]
  title = "Меню"
  image = ""
  description = """

  """
[params.portfolio]
  title = "Портфолио"
  image = "https://lh3.googleusercontent.com/HQ9UMvy7ndai-4a2tSgWuO1p6HZZmXljdD5_OEf1gg"
  description = """
  Компания имеет большой опыт в организации выездных банкетов. Наша компания одна из немногих , кто сегодня имеет такую материальную базу , которая позволяет обслужить 5000 и более гостей. Многие солидные и уважаемые компании доверили организацию и проведение своего корпоративного праздника.
  """
[params.places]
  title = "Площадки для мероприятий"
  image = "https://lh3.googleusercontent.com/W6SixUOHGvfEQAxFikg43crbuvnLASsco8KXCY41Zg"
  description = """
Подбор и аренда банкетных залов и открытых площадок для проведения мероприятий - чрезвычайно важный вопрос как для организаций, так и для частных лиц. Обладая уникальной федеральной базой разнобразных площадок вместимостью от 20 до 10 000 чел., менеджеры "Гильдии Кейтеринг" предложат вам вариант, подходящий исключительно для вашего мероприятия в вашем регионе. Многие солидные и уважаемые компании, VIP-персоны, селебрити и успешные предприниматели, а также небольшие компании и частные лица доверяют нам также организацию и проведение "под ключ" своих мероприятий.
  """
[params.news]
  title = "Новости"
  image = ""
  description = """

  """
[params.articles]
  title = "Статьи"
  image = ""
  description = """

  """


['']
  [[params.clients]]
    image = "https://lh3.googleusercontent.com/w3D_8uHuua7yb46xpg0GSMDkxDdL-G9_TiD_58MVNw"
    link = "http://gildia-catering.ru"
  [[params.clients]]
    image = "https://lh3.googleusercontent.com/dUae3JD7FTgxuVlPlzw8kDfaFaBT9feAbSd5d1Hz_g"
    link = "http://gildia-catering.ru"
  [[params.clients]]
    image = "https://lh3.googleusercontent.com/FM1u9a7d_H95gZeWsOmD9GfkQdptgHdSussfo1VCTQ"
    link = "http://gildia-catering.ru"
  [[params.clients]]
    image = "https://lh3.googleusercontent.com/rCcAfG5ZSS2uqvZMO8EFMn1XJcRkKRzxtBsDemYWPw"
    link = "http://gildia-catering.ru"
  [[params.clients]]
    image = "https://lh3.googleusercontent.com/qOLPRNWM8h60G-7zFIresbZqGjzBt06clQnLqtTHQg"
    link = "http://gildia-catering.ru"
  [[params.clients]]
    image = "https://lh3.googleusercontent.com/oCtJlhuqhm4nR2MaMwANwnYvdlqW56h8EYvZcKCnTQ"
    link = "http://gildia-catering.ru"
  [[params.clients]]
    image = "https://lh3.googleusercontent.com/IwtDMhIMa-Y6zZjwCmb6Alrbz-Ew8-nwAc8tOJx_IA"
    link = "http://gildia-catering.ru"
  [[params.clients]]
    image = "https://lh3.googleusercontent.com/a7Si1Exw6n2ibdK3t_RbzvubesBYl6iGiFo15pJE6g"
    link = "http://gildia-catering.ru"
  [[params.clients]]
    image = "https://lh3.googleusercontent.com/hdKsv83cvIbB7tNAQJLexWjhJ16YN6u48Aa8K31PHA"
    link = "http://gildia-catering.ru"
  [[params.clients]]
    image = "https://lh3.googleusercontent.com/D5lxU_d-Y5_bOTIVBGjeXxv3Pm4jnnu7kXcYizMsHA"
    link = "http://gildia-catering.ru"
  [[params.clients]]
    image = "https://lh3.googleusercontent.com/MW9JD1y93Dlzp16UHxDFiN2l_MwxSqA7X0C1US64rg"
    link = "http://gildia-catering.ru"
  [[params.clients]]
    image = "https://lh3.googleusercontent.com/E4kPqdig8hNwR0sYls54r4JSuYpxh6156-6MUh5LWw"
    link = "http://gildia-catering.ru"
  [[params.clients]]
    image = "https://lh3.googleusercontent.com/KSuFcY5xdyTEmh8TOKlP4L_UlF2iJB1Ie_Xs9l5jxA"
    link = "http://gildia-catering.ru"
  [[params.clients]]
    image = "https://lh3.googleusercontent.com/7Uvrl71J1FCtuVdtQ6XvV1gKa6XtDvrDVwNnLhTnIw"
    link = "http://gildia-catering.ru"
  [[params.clients]]
    image = "https://lh3.googleusercontent.com/Fk9_ucxCRh-D8fWpypZEUXAu-8bjkVHaLrzUfo7YrA"
    link = "http://gildia-catering.ru"
  [[params.clients]]
    image = "https://lh3.googleusercontent.com/RaPXUVbJK4dX6UQAFg4_ZTAWUhoXmFOI4X7kCRfEAg"
    link = "http://gildia-catering.ru"
  [[params.clients]]
    image = "https://lh3.googleusercontent.com/mzv__wF6Pv56jAR9LtGFy63vw2HuXf0c6cfiwLNleg"
    link = "http://gildia-catering.ru"
  [[params.clients]]
    image = "https://lh3.googleusercontent.com/IVhEF_vPjnBwRVyT2YTDprW_0MDZ84v2aSP4LPK6iA"
    link = "http://gildia-catering.ru"
  [[params.clients]]
    image = "https://lh3.googleusercontent.com/OJmO9r8dj9x96EQWOUKGJ5IooqRWv0VTgYBz4PuVgQ"
    link = "http://gildia-catering.ru"
  [[params.clients]]
    image = "https://lh3.googleusercontent.com/saf9pbZOvbIFhFDyLAYLjfzG2DP2KghCASASAF3BDw"
    link = "http://gildia-catering.ru"

[menu]
  [[menu.main]]
     name = "О нас"
     weight = 10
     url = "/about/"
  [[menu.main]]
    name = "Услуги"
    weight = 20
    identifier = "services"
    url = "/services/"
  [[menu.main]]
    name = "Портфолио"
    weight = 30
    url = "/portfolio/"
  [[menu.main]]
    name = "Меню"
    weight = 40
    url = "/menu/"
  [[menu.main]]
    name = "Клиенты"
    weight = 50
    url = "/clients/"
  [[menu.main]]
    name = "Площадки"
    weight = 60
    url = "/places/"
  [[menu.main]]
    name = "Новости"
    weight = 70
    url = "/news/"
  [[menu.main]]
    name = "Контакты"
    weight = 80
    url = "/contacts/"

  [[menu.footer]]
     name = "О нас"
     weight = 10
     url = "/about/"
  [[menu.footer]]
    name = "Услуги"
    weight = 20
    identifier = "services"
    url = "/services/"
  [[menu.footer]]
    name = "Портфолио"
    weight = 30
    url = "/portfolio/"
  [[menu.footer]]
    name = "Меню"
    weight = 40
    url = "/menu/"
  [[menu.footer]]
    name = "Площадки"
    weight = 60
    url = "/places/"
  [[menu.footer]]
    name = "Контакты"
    weight = 80
    url = "/contacts/"
